// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  pagiJump: string;
  pagiJumpText: string;
  pagiWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
